/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;


import java.awt.Component;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Tri
 */
public class ChuyenDichDongForm extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenDichDongForm
     */
    public ChuyenDichDongForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tareaEncryption = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtKeyEncryption = new javax.swing.JTextField();
        btnEncryption = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tareaDecryption = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtKeyDecryption = new javax.swing.JTextField();
        btnDecryption = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chuyển dịch dòng");

        tareaEncryption.setColumns(20);
        tareaEncryption.setRows(5);
        jScrollPane1.setViewportView(tareaEncryption);

        jLabel1.setText("key");

        btnEncryption.setText("Encryption");
        btnEncryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptionActionPerformed(evt);
            }
        });

        tareaDecryption.setColumns(20);
        tareaDecryption.setRows(5);
        jScrollPane2.setViewportView(tareaDecryption);

        jLabel2.setText("key");

        btnDecryption.setText("Decryption");
        btnDecryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEncryption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKeyEncryption)
                    .addComponent(txtKeyDecryption)
                    .addComponent(btnDecryption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtKeyEncryption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEncryption)))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKeyDecryption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addComponent(btnDecryption))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptionActionPerformed
        // TODO add your handling code here:
        String plainText = tareaEncryption.getText();
        String key = txtKeyEncryption.getText();
        
        plainText = formatInput(plainText);
        key = formatInput(key);
        String cipherText = "";
        
        boolean checkPlainText = check(plainText);
        boolean checkKey = check(key);
        
        if(!checkPlainText || !checkKey){
            JOptionPane.showMessageDialog(rootPane,"PlainText or Key invalid");
        }
        else{
            
            int number = plainText.length() % key .length();
            //if plaintext not fill matrix
            if(number !=0){
                //random character x -> z and append plaintext
                for(int i = 0; i < key.length()-number  ; i++){
                    int randomValue =(int) Math.round(Math.random()*2);
                    plainText += (char)(randomValue + 120);
                }
            }
            
            String[] arrayKey = key.split("");
            
            for(int i = 0; i < arrayKey.length ;i++){
                
                int index = findMinCharacterIndex(arrayKey);
                //character "{" = 123 in ascii 
                arrayKey[index] = "{";
                for(int j = index; j < plainText.length(); j+= arrayKey.length){
                    cipherText += plainText.charAt(j);
                }
            }
        }
        tareaDecryption.setText(cipherText);
    }//GEN-LAST:event_btnEncryptionActionPerformed

    private void btnDecryptionActionPerformed(java.awt.event.ActionEvent evt, Component frame) {//GEN-FIRST:event_btnDecryptionActionPerformed
          try
        {             
        String keyDecryption =   txtKeyDecryption.getText().replaceAll("\\s", "");
        String cipherText =  tareaDecryption.getText().replaceAll("\\s", "");
        if(keyDecryption.length()==0 || cipherText.length()==0)
             JOptionPane.showMessageDialog(frame, "Khong ��?c b? tr?ng");
        else
        {
            if(checkNumInString(keyDecryption) && checkNumInString(cipherText) )
            {
                 if(cipherText.length()%keyDecryption.length()==0){
                 String arraylainText=decryptCT(keyDecryption, cipherText);
                 tareaDecryption.setText(arraylainText);
                 }
                else{
                JOptionPane.showMessageDialog(frame, "CipherText ph?i chia h?t cho key");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(frame, "Key v� cipherText kh�ng ��?c ch?a s?");
            }
        }
        }
         catch(Exception  e){
         JOptionPane.showMessageDialog(frame, e);
       } 
    }//GEN-LAST:event_btnDecryptionActionPerformed
     public static String decryptCT(String key, String text) {
        int[] arrange = arrangeKey(key);
        int lenkey = arrange.length;
        int lentext = text.length();
        int row = (int) Math.ceil((double) lentext / lenkey);
        String regex = "(?<=\\G.{" + row + "})";
        String[] get = text.split(regex);

        char[][] grid = new char[row][lenkey];

        for (int x = 0; x < lenkey; x++) {
            for (int y = 0; y < lenkey; y++) {
                if (arrange[x] == y) {
                    for (int z = 0; z < row; z++) {
                        grid[z][y] = get[arrange[y]].charAt(z);
                    }
                }
            }
        }
        String dec = "";
        for (int x = 0; x < row; x++) {
            for (int y = 0; y < lenkey; y++) {
                dec = dec + grid[x][y];
            }
        }

        return dec;
    }
     public static int[] arrangeKey(String key) {
        //arrange position of grid
        String[] keys = key.split("");
        Arrays.sort(keys);
        int[] num = new int[key.length()];
        for (int x = 0; x < keys.length; x++) {
            for (int y = 0; y < key.length(); y++) {
                if (keys[x].equals(key.charAt(y) + "")) {
                    num[y] = x;
                    break;
                }
            }
        }
        return num;
    }
     private static boolean checkNumInString(String key)
    {
         if(key.matches(".*\\d.*")==true)
          return false;        
        return true;
                  
    }
    
    private int findMinCharacterIndex(String[]array){
        String maxCharacter = array[0];
        int index = 0;
        for(int i = 0; i < array.length; i++){
            
            if(maxCharacter.compareTo(array[i]) > 0){
                index = i;
                maxCharacter = array[i];
            }
        }
        return index;
    }
    private String formatInput(String str){
        
        str = str.toLowerCase().trim().replaceAll("\\s{1,}","");
        return str;
    }
     private boolean check(String string){
        if(string.length()==0){
            return false;
        }
        for(int i = 0; i < string.length() ; i++){
            if(string.codePointAt(i) < 97 || string.codePointAt(i) > 122 ){
                return false;
            }
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenDichDongForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenDichDongForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenDichDongForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenDichDongForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenDichDongForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecryption;
    private javax.swing.JButton btnEncryption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tareaDecryption;
    private javax.swing.JTextArea tareaEncryption;
    private javax.swing.JTextField txtKeyDecryption;
    private javax.swing.JTextField txtKeyEncryption;
    // End of variables declaration//GEN-END:variables
}
